var busArray = [{start:"普陀",end:"安庆",end_station:"安庆",bus_time:"8:15",bus_tick:"265元"},
{start:"新城",end:"安庆",end_station:"安庆",bus_time:"8:35",bus_tick:"263元"},
{start:"定海",end:"安庆",end_station:"安庆",bus_time:"9:05",bus_tick:"258元"},
{start:"普陀",end:"上虞",end_station:"上虞",bus_time:"7:35",bus_tick:"64元"},
{start:"普陀",end:"慈溪",end_station:"慈溪",bus_time:"8:30",bus_tick:"62元"},
{start:"普陀",end:"慈溪",end_station:"慈溪",bus_time:"12:20",bus_tick:"65元"},
{start:"普陀",end:"上虞",end_station:"上虞",bus_time:"13:20",bus_tick:"64元"},
{start:"新城",end:"上虞",end_station:"上虞",bus_time:"7:55",bus_tick:"62元"},
{start:"新城",end:"慈溪",end_station:"慈溪",bus_time:"8:48",bus_tick:"60元"},
{start:"新城",end:"慈溪",end_station:"慈溪",bus_time:"12:40",bus_tick:"63元"},
{start:"新城",end:"上虞",end_station:"上虞",bus_time:"13:40",bus_tick:"62元"},
{start:"定海",end:"上虞",end_station:"上虞",bus_time:"8:25",bus_tick:"57元"},
{start:"定海",end:"慈溪",end_station:"慈溪",bus_time:"9:20",bus_tick:"56元"},
{start:"定海",end:"慈溪",end_station:"慈溪",bus_time:"13:15",bus_tick:"59元"},
{start:"定海",end:"上虞",end_station:"上虞",bus_time:"14:10",bus_tick:"57元"},
{start:"普陀",end:"奉化",end_station:"奉化",bus_time:"7:45",bus_tick:"62元"},
{start:"普陀",end:"宁海",end_station:"宁海",bus_time:"8:55",bus_tick:"66元"},
{start:"普陀",end:"奉化",end_station:"奉化",bus_time:"12:30",bus_tick:"62元"},
{start:"新城",end:"奉化",end_station:"奉化",bus_time:"8:10",bus_tick:"60元"},
{start:"新城",end:"宁海",end_station:"宁海",bus_time:"9:20",bus_tick:"64元"},
{start:"新城",end:"奉化",end_station:"奉化",bus_time:"12:50",bus_tick:"60元"},
{start:"定海",end:"奉化",end_station:"奉化",bus_time:"8:40",bus_tick:"56元"},
{start:"定海",end:"宁海",end_station:"宁海",bus_time:"9:50",bus_tick:"59元"},
{start:"定海",end:"奉化",end_station:"奉化",bus_time:"13:20",bus_tick:"56元"},
{start:"普陀",end:"阜阳",end_station:"阜阳",bus_time:"15:20",bus_tick:"200元"},
{start:"普陀",end:"阜阳",end_station:"阜阳",bus_time:"15:30",bus_tick:"200元"},
{start:"普陀",end:"阜阳",end_station:"阜阳",bus_time:"15:40",bus_tick:"200元"},
{start:"新城",end:"阜阳",end_station:"阜阳",bus_time:"15:40",bus_tick:"198元"},
{start:"新城",end:"阜阳",end_station:"阜阳",bus_time:"15:50",bus_tick:"198元"},
{start:"新城",end:"阜阳",end_station:"阜阳",bus_time:"16:00",bus_tick:"198元"},
{start:"定海",end:"阜阳",end_station:"阜阳",bus_time:"16:10",bus_tick:"195元"},
{start:"定海",end:"阜阳",end_station:"阜阳",bus_time:"16:25",bus_tick:"195元"},
{start:"定海",end:"阜阳",end_station:"阜阳",bus_time:"16:30",bus_tick:"195元"},
{start:"普陀",end:"杭州",end_station:" 杭州南站",bus_time:"6:00",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州九堡",bus_time:"6:26",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州南站",bus_time:"6:57",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州九堡",bus_time:"7:28",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州南站",bus_time:"7:59",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州九堡",bus_time:"8:15",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州南站",bus_time:"8:30",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州九堡",bus_time:"9:09",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州南站",bus_time:"9:25",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州九堡",bus_time:"9:40",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州南站",bus_time:"10:11",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州九堡",bus_time:"10:42",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州南站",bus_time:"11:08",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州九堡",bus_time:"11:39",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州南站",bus_time:"12:10",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州九堡",bus_time:"12:36",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州南站",bus_time:"13:02",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州南站",bus_time:"13:33",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州九堡",bus_time:"14:20",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州南站",bus_time:"14:35",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州南站",bus_time:"15:06",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州九堡",bus_time:"15:37",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州南站",bus_time:"16:10",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州九堡",bus_time:"16:45",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州南站",bus_time:"17:15",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州九堡",bus_time:"17:45",bus_tick:"95元"},
{start:"普陀",end:"杭州",end_station:" 杭州南站",bus_time:"18:15",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州南站",bus_time:"6:18",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州九堡",bus_time:"6:44",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州南站",bus_time:"7:17",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州九堡",bus_time:"7:48",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州南站",bus_time:"8:20",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州九堡",bus_time:"8:35",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州南站",bus_time:"8:50",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州九堡",bus_time:"9:27",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州九堡",bus_time:"9:58",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州九堡",bus_time:"10:20",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州南站",bus_time:"10:29",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州九堡",bus_time:"11:00",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州南站",bus_time:"11:26",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州九堡",bus_time:"11:57",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州南站",bus_time:"12:28",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州九堡",bus_time:"12:54",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州南站",bus_time:"13:20",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州九堡",bus_time:"13:40",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州南站",bus_time:"13:52",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州九堡",bus_time:"14:40",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州南站",bus_time:"14:55",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州九堡",bus_time:"15:10",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州九堡",bus_time:"15:54",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州南站",bus_time:"16:28",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州九堡",bus_time:"17:05",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州南站",bus_time:"17:40",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州九堡",bus_time:"18:05",bus_tick:"95元"},
{start:"新城",end:"杭州",end_station:" 杭州南站",bus_time:"18:33",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州南站",bus_time:"6:45",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州九堡",bus_time:"7:10",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州南站",bus_time:"7:50",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州九堡",bus_time:"8:20",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州南站",bus_time:"8:50",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州九堡",bus_time:"9:05",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州南站",bus_time:"9:20",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州九堡",bus_time:"9:40",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州九堡",bus_time:"9:55",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州南站",bus_time:"10:10",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州九堡",bus_time:"10:50",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州南站",bus_time:"11:00",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州九堡",bus_time:"11:30",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州南站",bus_time:"11:55",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州九堡",bus_time:"12:25",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州南站",bus_time:"12:55",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州九堡",bus_time:"13:20",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州南站",bus_time:"13:45",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州九堡",bus_time:"14:10",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州南站",bus_time:"14:20",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州九堡",bus_time:"15:10",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州南站",bus_time:"15:25",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州九堡",bus_time:"15:40",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州南站",bus_time:"15:50",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州九堡",bus_time:"16:25",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州南站",bus_time:"16:55",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州九堡",bus_time:"17:35",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州南站",bus_time:"18:12",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州九堡",bus_time:"18:35",bus_tick:"95元"},
{start:"定海",end:"杭州",end_station:" 杭州南站",bus_time:"19:00",bus_tick:"95元"},
{start:"普陀",end:"毫州",end_station:"毫州",bus_time:"9:00",bus_tick:"200元"},
{start:"新城",end:"毫州",end_station:"毫州",bus_time:"9:20",bus_tick:"198元"},
{start:"定海",end:"毫州",end_station:"毫州",bus_time:"9:50",bus_tick:"195元"},
{start:"定海",end:"淮安",end_station:"淮安",bus_time:"7:05",bus_tick:"222元"},
{start:"普陀",end:"金华",end_station:"金华",bus_time:"8:30",bus_tick:"150元"},
{start:"普陀",end:"江山",end_station:"江山",bus_time:"8:55",bus_tick:"126元"},
{start:"普陀",end:"兰溪",end_station:"兰溪",bus_time:"11:15",bus_tick:"141元"},
{start:"普陀",end:"金华",end_station:"金华",bus_time:"14:40",bus_tick:"150元"},
{start:"新城",end:"金华",end_station:"金华",bus_time:"8:50",bus_tick:"148元"},
{start:"新城",end:"江山",end_station:"江山",bus_time:"9:15",bus_tick:"132元"},
{start:"新城",end:"兰溪",end_station:"兰溪",bus_time:"11:35",bus_tick:"124元"},
{start:"新城",end:"金华",end_station:"金华",bus_time:"15:00",bus_tick:"148元"},
{start:"定海",end:"金华",end_station:"金华",bus_time:"9:27",bus_tick:"143元"},
{start:"定海",end:"江山",end_station:"江山",bus_time:"9:45",bus_tick:"128元"},
{start:"定海",end:"兰溪",end_station:"兰溪",bus_time:"12:05",bus_tick:"119元"},
{start:"定海",end:"金华",end_station:"金华",bus_time:"15:30",bus_tick:"143元"},
{start:"普陀",end:"南京",end_station:"南京",bus_time:"7:40",bus_tick:"218元"},
{start:"新城",end:"南京",end_station:"南京",bus_time:"8:00",bus_tick:"216元"},
{start:"定海",end:"南京",end_station:"南京",bus_time:"8:30",bus_tick:"210元"},
{start:"普陀",end:"南浔",end_station:"南浔",bus_time:"8:35",bus_tick:"145元"},
{start:"普陀",end:"南浔",end_station:"南浔",bus_time:"14:35",bus_tick:"142元"},
{start:"普陀",end:"长兴",end_station:"长兴",bus_time:"15:05",bus_tick:"128元"},
{start:"新城",end:"南浔",end_station:"南浔",bus_time:"8:55",bus_tick:"143元"},
{start:"新城",end:"南浔",end_station:"南浔",bus_time:"14:55",bus_tick:"140元"},
{start:"新城",end:"长兴",end_station:"长兴",bus_time:"15:25",bus_tick:"126元"},
{start:"定海",end:"南浔",end_station:"南浔",bus_time:"9:25",bus_tick:"140元"},
{start:"定海",end:"南浔",end_station:"南浔",bus_time:"15:30",bus_tick:"134元"},
{start:"定海",end:"长兴",end_station:"长兴",bus_time:"15:55",bus_tick:"123元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"5:40",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波北站",bus_time:"6:00",bus_tick:"48元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"6:10",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"6:30",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"6:55",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波东站",bus_time:"7:10",bus_tick:"48元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"7:15",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"7:25",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波北站",bus_time:"7:40",bus_tick:"48元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"7:50",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波东站",bus_time:"8:05",bus_tick:"48元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"8:20",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波北站",bus_time:"8:35",bus_tick:"48元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"8:45",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"8:50",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"8:55",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"9:10",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"9:20",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波北站",bus_time:"9:30",bus_tick:"48元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"9:35",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"9:45",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"9:55",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波北站",bus_time:"10:05",bus_tick:"48元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"10:15",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"10:30",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波北站",bus_time:"10:45",bus_tick:"48元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"10:50",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"11:20",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波东站",bus_time:"11:35",bus_tick:"48元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"12:00",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波北站",bus_time:"12:15",bus_tick:"48元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"12:25",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"12:40",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波东站",bus_time:"12:45",bus_tick:"48元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"12:55",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波北站",bus_time:"13:05",bus_tick:"48元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"13:20",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波东站",bus_time:"13:30",bus_tick:"48元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"13:35",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"13:45",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波北站",bus_time:"14:00",bus_tick:"48元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"14:10",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"14:25",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波北站",bus_time:"14:30",bus_tick:"48元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"14:40",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波东站",bus_time:"14:50",bus_tick:"48元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"15:05",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"15:15",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波北站",bus_time:"15:20",bus_tick:"48元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"15:30",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波东站",bus_time:"15:40",bus_tick:"48元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"15:50",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"16:00",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波北站",bus_time:"16:10",bus_tick:"48元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"16:25",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波北站",bus_time:"16:40",bus_tick:"48元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"16:50",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波东站",bus_time:"17:00",bus_tick:"48元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"17:45",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波东站",bus_time:"18:00",bus_tick:"48元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"18:15",bus_tick:"49元"},
{start:"普陀",end:"宁波",end_station:" 宁波南站",bus_time:"19:00",bus_tick:"49元"},
{start:"新城",end:"宁波",end_station:" 宁波北站",bus_time:"6:20",bus_tick:"46元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"6:30",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"6:50",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"7:15",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波东站",bus_time:"7:30",bus_tick:"46元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"7:35",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"7:45",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波北站",bus_time:"8:00",bus_tick:"46元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"8:10",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波东站",bus_time:"8:25",bus_tick:"46元"},
{start:"新城",end:"宁波",end_station:" 宁波北站",bus_time:"8:55",bus_tick:"46元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"9:05",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"9:10",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"9:15",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"9:30",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"9:40",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波北站",bus_time:"9:50",bus_tick:"46元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"9:55",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"10:05",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"10:15",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"10:35",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波北站",bus_time:"11:05",bus_tick:"46元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"11:10",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"11:40",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波东站",bus_time:"11:55",bus_tick:"46元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"12:20",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波北站",bus_time:"12:35",bus_tick:"46元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"12:45",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波东站",bus_time:"13:05",bus_tick:"46元"},
{start:"新城",end:"宁波",end_station:" 宁波北站",bus_time:"13:25",bus_tick:"46元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"13:40",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波东站",bus_time:"13:50",bus_tick:"46元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"13:55",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"14:05",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波北站",bus_time:"14:20",bus_tick:"46元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"14:30",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"14:45",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波北站",bus_time:"14:50",bus_tick:"46元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"15:00",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波东站",bus_time:"15:10",bus_tick:"46元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"15:25",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波北站",bus_time:"15:40",bus_tick:"46元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"15:50",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波东站",bus_time:"16:00",bus_tick:"46元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"16:10",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"16:20",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波北站",bus_time:"16:30",bus_tick:"46元"},
{start:"新城",end:"宁波",end_station:" 宁波北站",bus_time:"17:00",bus_tick:"46元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"17:10",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波东站",bus_time:"17:20",bus_tick:"46元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"18:05",bus_tick:"47元"},
{start:"新城",end:"宁波",end_station:" 宁波东站",bus_time:"18:20",bus_tick:"46元"},
{start:"新城",end:"宁波",end_station:" 宁波南站",bus_time:"18:35",bus_tick:"47元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"6:25",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波北站",bus_time:"6:50",bus_tick:"42元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"7:00",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"7:20",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"7:45",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波东站",bus_time:"8:00",bus_tick:"42元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"8:05",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"8:15",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波北站",bus_time:"8:30",bus_tick:"42元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"8:40",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波东站",bus_time:"8:55",bus_tick:"42元"},
{start:"定海",end:"宁波",end_station:"宁波南站",bus_time:"9:15",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波北站",bus_time:"9:25",bus_tick:"42元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"9:35",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"9:40",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"9:45",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"10:00",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"10:10",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波北站",bus_time:"10:20",bus_tick:"42元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"10:25",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"10:35",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"10:45",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波北站",bus_time:"10:55",bus_tick:"42元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"11:05",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"11:15",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波北站",bus_time:"11:35",bus_tick:"42元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"11:40",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"12:10",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:"宁波南站",bus_time:"12:20",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波东站",bus_time:"12:25",bus_tick:"42元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"12:50",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波北站",bus_time:"13:05",bus_tick:"42元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"13:15",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"13:25",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波东站",bus_time:"13:35",bus_tick:"42元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"13:40",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波北站",bus_time:"13:55",bus_tick:"42元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"14:10",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波东站",bus_time:"14:20",bus_tick:"42元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"14:25",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"14:35",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波北站",bus_time:"14:50",bus_tick:"42元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"15:00",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"15:10",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波北站",bus_time:"15:20",bus_tick:"42元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"15:30",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波东站",bus_time:"15:40",bus_tick:"42元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"15:55",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"16:00",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波北站",bus_time:"16:10",bus_tick:"42元"},
{start:"定海",end:"宁波",end_station:"宁波南站",bus_time:"16:15",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"16:20",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波东站",bus_time:"16:30",bus_tick:"42元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"16:40",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"16:50",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波北站",bus_time:"17:00",bus_tick:"42元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"17:10",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波北站",bus_time:"17:30",bus_tick:"42元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"17:40",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波东站",bus_time:"17:50",bus_tick:"42元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"18:33",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波东站",bus_time:"18:50",bus_tick:"42元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"19:05",bus_tick:"43元"},
{start:"定海",end:"宁波",end_station:" 宁波南站",bus_time:"19:45",bus_tick:"43元"},
{start:"普陀",end:"日照",end_station:"日照",bus_time:"8:05",bus_tick:"350元"},
{start:"普陀",end:"潍坊",end_station:"潍坊",bus_time:"10:00",bus_tick:"350元"},
{start:"新城",end:"日照",end_station:"日照",bus_time:"8:25",bus_tick:"348元"},
{start:"新城",end:"潍坊",end_station:"潍坊",bus_time:"10:20",bus_tick:"348元"},
{start:"定海",end:"日照",end_station:"日照",bus_time:"9:05",bus_tick:"343元"},
{start:"定海",end:"潍坊",end_station:"潍坊",bus_time:"10:50",bus_tick:"343元"},
{start:"普陀",end:"瑞安",end_station:"瑞安",bus_time:"8:00",bus_tick:"135元"},
{start:"普陀",end:"温州",end_station:"温州",bus_time:"8:50",bus_tick:"158元"},
{start:"普陀",end:"柳市",end_station:"柳市",bus_time:"9:20",bus_tick:"133元"},
{start:"普陀",end:"瑞安",end_station:"瑞安",bus_time:"14:40",bus_tick:"135元"},
{start:"新城",end:"瑞安",end_station:"瑞安",bus_time:"8:19",bus_tick:"133元"},
{start:"新城",end:"温州",end_station:"温州",bus_time:"9:10",bus_tick:"156元"},
{start:"新城",end:"柳市",end_station:"柳市",bus_time:"9:45",bus_tick:"131元"},
{start:"新城",end:"瑞安",end_station:"瑞安",bus_time:"15:00",bus_tick:"133元"},
{start:"定海",end:"瑞安",end_station:"瑞安",bus_time:"8:50",bus_tick:"127元"},
{start:"定海",end:"温州",end_station:"温州",bus_time:"9:40",bus_tick:"149元"},
{start:"定海",end:"柳市",end_station:"柳市",bus_time:"10:15",bus_tick:"127元"},
{start:"定海",end:"瑞安",end_station:"瑞安",bus_time:"15:35",bus_tick:"127元"},
{start:"普陀",end:"三门",end_station:"三门",bus_time:"8:00",bus_tick:"84元"},
{start:"普陀",end:"三门",end_station:"三门",bus_time:"13:15",bus_tick:"84元"},
{start:"新城",end:"三门",end_station:"三门",bus_time:"8:20",bus_tick:"82元"},
{start:"新城",end:"三门",end_station:"三门",bus_time:"13:35",bus_tick:"82元"},
{start:"定海",end:"三门",end_station:"三门",bus_time:"9:00",bus_tick:"78元"},
{start:"定海",end:"三门",end_station:"三门",bus_time:"14:00",bus_tick:"78元"},
{start:"普陀",end:"上海",end_station:" 上海南站",bus_time:"5:50",bus_tick:"130元"},
{start:"普陀",end:"上海",end_station:" 上海南站",bus_time:"6:30",bus_tick:"138元"},
{start:"普陀",end:"上海",end_station:" 上海南站",bus_time:"7:10",bus_tick:"130元"},
{start:"普陀",end:"上海",end_station:" 上海南站",bus_time:"7:50",bus_tick:"130元"},
{start:"普陀",end:"上海",end_station:" 上海南站",bus_time:"8:30",bus_tick:"130元"},
{start:"普陀",end:"上海",end_station:" 上海南站",bus_time:"9:10",bus_tick:"138元"},
{start:"普陀",end:"上海",end_station:" 上海南站",bus_time:"9:50",bus_tick:"130元"},
{start:"普陀",end:"上海",end_station:" 上海南站",bus_time:"10:25",bus_tick:"138元"},
{start:"普陀",end:"上海",end_station:" 上海南站",bus_time:"10:55",bus_tick:"138元"},
{start:"普陀",end:"上海",end_station:" 上海南站",bus_time:"11:25",bus_tick:"130元"},
{start:"普陀",end:"上海",end_station:" 上海南站",bus_time:"11:55",bus_tick:"130元"},
{start:"普陀",end:"上海",end_station:" 上海南站",bus_time:"12:25",bus_tick:"130元"},
{start:"普陀",end:"上海",end_station:" 上海南站",bus_time:"12:55",bus_tick:"130元"},
{start:"普陀",end:"上海",end_station:" 上海南站",bus_time:"13:25",bus_tick:"130元"},
{start:"普陀",end:"上海",end_station:" 上海南站",bus_time:"13:55",bus_tick:"130元"},
{start:"普陀",end:"上海",end_station:" 上海南站",bus_time:"14:30",bus_tick:"130元"},
{start:"普陀",end:"上海",end_station:" 上海南站",bus_time:"15:10",bus_tick:"130元"},
{start:"普陀",end:"上海",end_station:" 上海南站",bus_time:"16:10",bus_tick:"130元"},
{start:"普陀",end:"上海",end_station:" 上海南站",bus_time:"16:50",bus_tick:"130元"},
{start:"普陀",end:"上海",end_station:" 上海南站",bus_time:"17:30",bus_tick:"130元"},
{start:"普陀",end:"上海",end_station:" 上海南站",bus_time:"18:10",bus_tick:"130元"},
{start:"新城",end:"上海",end_station:" 上海南站",bus_time:"6:10",bus_tick:"130元"},
{start:"新城",end:"上海",end_station:" 上海南站",bus_time:"6:50",bus_tick:"138元"},
{start:"新城",end:"上海",end_station:" 上海南站",bus_time:"7:30",bus_tick:"130元"},
{start:"新城",end:"上海",end_station:" 上海南站",bus_time:"8:10",bus_tick:"130元"},
{start:"新城",end:"上海",end_station:" 上海南站",bus_time:"8:48",bus_tick:"130元"},
{start:"新城",end:"上海",end_station:" 上海南站",bus_time:"9:28",bus_tick:"138元"},
{start:"新城",end:"上海",end_station:" 上海南站",bus_time:"10:08",bus_tick:"130元"},
{start:"新城",end:"上海",end_station:" 上海南站",bus_time:"10:43",bus_tick:"138元"},
{start:"新城",end:"上海",end_station:" 上海南站",bus_time:"11:13",bus_tick:"138元"},
{start:"新城",end:"上海",end_station:" 上海南站",bus_time:"11:43",bus_tick:"130元"},
{start:"新城",end:"上海",end_station:" 上海南站",bus_time:"12:15",bus_tick:"130元"},
{start:"新城",end:"上海",end_station:" 上海南站",bus_time:"12:45",bus_tick:"130元"},
{start:"新城",end:"上海",end_station:" 上海南站",bus_time:"13:15",bus_tick:"130元"},
{start:"新城",end:"上海",end_station:" 上海南站",bus_time:"13:45",bus_tick:"130元"},
{start:"新城",end:"上海",end_station:" 上海南站",bus_time:"14:15",bus_tick:"130元"},
{start:"新城",end:"上海",end_station:" 上海南站",bus_time:"14:49",bus_tick:"130元"},
{start:"新城",end:"上海",end_station:" 上海南站",bus_time:"15:30",bus_tick:"130元"},
{start:"新城",end:"上海",end_station:" 上海南站",bus_time:"16:30",bus_tick:"130元"},
{start:"新城",end:"上海",end_station:" 上海南站",bus_time:"17:10",bus_tick:"130元"},
{start:"新城",end:"上海",end_station:" 上海南站",bus_time:"17:48",bus_tick:"130元"},
{start:"新城",end:"上海",end_station:" 上海南站",bus_time:"18:28",bus_tick:"130元"},
{start:"定海",end:"上海",end_station:" 上海南站",bus_time:"6:40",bus_tick:"130元"},
{start:"定海",end:"上海",end_station:" 上海南站",bus_time:"7:20",bus_tick:"138元"},
{start:"定海",end:"上海",end_station:" 上海南站",bus_time:"8:05",bus_tick:"130元"},
{start:"定海",end:"上海",end_station:" 上海南站",bus_time:"8:40",bus_tick:"130元"},
{start:"定海",end:"上海",end_station:" 上海南站",bus_time:"9:15",bus_tick:"130元"},
{start:"定海",end:"上海",end_station:" 上海南站",bus_time:"10:00",bus_tick:"138元"},
{start:"定海",end:"上海",end_station:" 上海南站",bus_time:"10:40",bus_tick:"130元"},
{start:"定海",end:"上海",end_station:" 上海南站",bus_time:"11:15",bus_tick:"138元"},
{start:"定海",end:"上海",end_station:" 上海南站",bus_time:"11:40",bus_tick:"138元"},
{start:"定海",end:"上海",end_station:" 上海南站",bus_time:"12:10",bus_tick:"130元"},
{start:"定海",end:"上海",end_station:" 上海南站",bus_time:"12:45",bus_tick:"130元"},
{start:"定海",end:"上海",end_station:" 上海南站",bus_time:"13:15",bus_tick:"130元"},
{start:"定海",end:"上海",end_station:" 上海南站",bus_time:"13:40",bus_tick:"130元"},
{start:"定海",end:"上海",end_station:" 上海南站",bus_time:"14:15",bus_tick:"130元"},
{start:"定海",end:"上海",end_station:" 上海南站",bus_time:"14:45",bus_tick:"130元"},
{start:"定海",end:"上海",end_station:" 上海南站",bus_time:"15:20",bus_tick:"130元"},
{start:"定海",end:"上海",end_station:" 上海南站",bus_time:"16:00",bus_tick:"130元"},
{start:"定海",end:"上海",end_station:" 上海南站",bus_time:"17:00",bus_tick:"130元"},
{start:"定海",end:"上海",end_station:" 上海南站",bus_time:"17:40",bus_tick:"130元"},
{start:"定海",end:"上海",end_station:" 上海南站",bus_time:"18:20",bus_tick:"130元"},
{start:"定海",end:"上海",end_station:" 上海南站",bus_time:"18:55",bus_tick:"130元"},
{start:"普陀",end:"水头",end_station:"水头",bus_time:"11:50",bus_tick:"168元"},
{start:"新城",end:"水头",end_station:"水头",bus_time:"8:00",bus_tick:"166元"},
{start:"定海",end:"水头",end_station:"水头",bus_time:"8:30",bus_tick:"160元"},
{start:"普陀",end:"温岭",end_station:"温岭",bus_time:"8:00",bus_tick:"99元"},
{start:"普陀",end:"椒江",end_station:"椒江",bus_time:"8:50",bus_tick:"109元"},
{start:"普陀",end:"松门",end_station:"松门",bus_time:"12:40",bus_tick:"96元"},
{start:"普陀",end:"椒江",end_station:"椒江",bus_time:"14:20",bus_tick:"96元"},
{start:"普陀",end:"路桥",end_station:"路桥",bus_time:"15:00",bus_tick:"99元"},
{start:"新城",end:"温岭",end_station:"温岭",bus_time:"8:20",bus_tick:"97元"},
{start:"新城",end:"椒江",end_station:"椒江",bus_time:"9:10",bus_tick:"107元"},
{start:"新城",end:"松门",end_station:"松门",bus_time:"13:00",bus_tick:"94元"},
{start:"新城",end:"椒江",end_station:"椒江",bus_time:"14:40",bus_tick:"94元"},
{start:"新城",end:"路桥",end_station:"路桥",bus_time:"15:20",bus_tick:"97元"},
{start:"定海",end:"温岭",end_station:"温岭",bus_time:"8:55",bus_tick:"92元"},
{start:"定海",end:"椒江",end_station:"椒江",bus_time:"9:45",bus_tick:"101元"},
{start:"定海",end:"松门",end_station:"松门",bus_time:"13:35",bus_tick:"90元"},
{start:"定海",end:"椒江",end_station:"椒江",bus_time:"15:15",bus_tick:"90元"},
{start:"定海",end:"路桥",end_station:"路桥",bus_time:"15:50",bus_tick:"92元"},
{start:"普陀",end:"萧山",end_station:"萧山",bus_time:"7:50",bus_tick:"100元"},
{start:"普陀",end:"柯桥",end_station:"柯桥",bus_time:"12:20",bus_tick:"85元"},
{start:"新城",end:"萧山",end_station:"萧山",bus_time:"8:10",bus_tick:"98元"},
{start:"新城",end:"柯桥",end_station:"柯桥",bus_time:"12:37",bus_tick:"83元"},
{start:"定海",end:"萧山",end_station:"萧山",bus_time:"8:45",bus_tick:"95元"},
{start:"定海",end:"柯桥",end_station:"柯桥",bus_time:"13:10",bus_tick:"79元"},
{start:"普陀",end:"绍兴",end_station:"绍兴",bus_time:"8:35",bus_tick:"92元"},
{start:"普陀",end:"诸暨",end_station:"诸暨",bus_time:"9:15",bus_tick:"100元"},
{start:"普陀",end:"绍兴",end_station:"绍兴",bus_time:"13:30",bus_tick:"92元"},
{start:"普陀",end:"诸暨",end_station:"诸暨",bus_time:"14:30",bus_tick:"100元"},
{start:"新城",end:"绍兴",end_station:"绍兴",bus_time:"8:57",bus_tick:"90元"},
{start:"新城",end:"诸暨",end_station:"诸暨",bus_time:"9:35",bus_tick:"98元"},
{start:"新城",end:"绍兴",end_station:"绍兴",bus_time:"13:52",bus_tick:"90元"},
{start:"新城",end:"诸暨",end_station:"诸暨",bus_time:"14:48",bus_tick:"98元"},
{start:"定海",end:"绍兴",end_station:"绍兴",bus_time:"9:25",bus_tick:"87元"},
{start:"定海",end:"诸暨",end_station:"诸暨",bus_time:"10:05",bus_tick:"95元"},
{start:"定海",end:"绍兴",end_station:"绍兴",bus_time:"14:22",bus_tick:"87元"},
{start:"定海",end:"诸暨",end_station:"诸暨",bus_time:"15:20",bus_tick:"95元"},
{start:"普陀",end:"盐城",end_station:"盐城",bus_time:"7:25",bus_tick:"114元"},
{start:"普陀",end:"苏州",end_station:"苏州",bus_time:"8:25",bus_tick:"130元"},
{start:"普陀",end:"无锡",end_station:"无锡",bus_time:"9:40",bus_tick:"148元"},
{start:"普陀",end:"嘉兴",end_station:"嘉兴",bus_time:"10:20",bus_tick:"125元"},
{start:"普陀",end:"嘉兴",end_station:"嘉兴",bus_time:"13:35",bus_tick:"117元"},
{start:"新城",end:"盐城",end_station:"盐城",bus_time:"7:45",bus_tick:"112元"},
{start:"新城",end:"苏州",end_station:"苏州",bus_time:"8:45",bus_tick:"128元"},
{start:"新城",end:"无锡",end_station:"无锡",bus_time:"10:00",bus_tick:"146元"},
{start:"新城",end:"嘉兴",end_station:"嘉兴",bus_time:"10:40",bus_tick:"123元"},
{start:"新城",end:"嘉兴",end_station:"嘉兴",bus_time:"13:55",bus_tick:"115元"},
{start:"定海",end:"盐城",end_station:"盐城",bus_time:"8:15",bus_tick:"108元"},
{start:"定海",end:"苏州",end_station:"苏州",bus_time:"9:25",bus_tick:"123元"},
{start:"定海",end:"无锡",end_station:"无锡",bus_time:"10:30",bus_tick:"139元"},
{start:"定海",end:"嘉兴",end_station:"嘉兴",bus_time:"11:10",bus_tick:"120元"},
{start:"定海",end:"嘉兴",end_station:"嘉兴",bus_time:"14:25",bus_tick:"110元"},
{start:"普陀",end:"义乌",end_station:"义乌",bus_time:"7:00",bus_tick:"111元"},
{start:"普陀",end:"永康",end_station:"永康",bus_time:"7:55",bus_tick:"104元"},
{start:"普陀",end:"义乌",end_station:"义乌",bus_time:"8:25",bus_tick:"111元"},
{start:"普陀",end:"丽水",end_station:"丽水",bus_time:"9:10",bus_tick:"115元"},
{start:"普陀",end:"义乌",end_station:"义乌",bus_time:"14:10",bus_tick:"111元"},
{start:"普陀",end:"义乌",end_station:"义乌",bus_time:"16:10",bus_tick:"111元"},
{start:"新城",end:"义乌",end_station:"义乌",bus_time:"7:20",bus_tick:"109元"},
{start:"新城",end:"永康",end_station:"永康",bus_time:"8:20",bus_tick:"102元"},
{start:"新城",end:"义乌",end_station:"义乌",bus_time:"8:46",bus_tick:"109元"},
{start:"新城",end:"丽水",end_station:"丽水",bus_time:"9:30",bus_tick:"113元"},
{start:"新城",end:"义乌",end_station:"义乌",bus_time:"14:28",bus_tick:"109元"},
{start:"新城",end:"义乌",end_station:"义乌",bus_time:"16:30",bus_tick:"109元"},
{start:"定海",end:"义乌",end_station:"义乌",bus_time:"7:50",bus_tick:"105元"},
{start:"定海",end:"永康",end_station:"永康",bus_time:"8:50",bus_tick:"97元"},
{start:"定海",end:"义乌",end_station:"义乌",bus_time:"9:15",bus_tick:"105元"},
{start:"定海",end:"丽水",end_station:"丽水",bus_time:"10:00",bus_tick:"107元"},
{start:"定海",end:"义乌",end_station:"义乌",bus_time:"15:05",bus_tick:"105元"},
{start:"定海",end:"义乌",end_station:"义乌",bus_time:"17:05",bus_tick:"105元"},
{start:"普陀",end:"余姚",end_station:"余姚",bus_time:"8:05",bus_tick:"58元"},
{start:"普陀",end:"余姚",end_station:"余姚",bus_time:"13:55",bus_tick:"58元"},
{start:"新城",end:"余姚",end_station:"余姚",bus_time:"8:25",bus_tick:"56元"},
{start:"新城",end:"余姚",end_station:"余姚",bus_time:"14:15",bus_tick:"56元"},
{start:"定海",end:"余姚",end_station:"余姚",bus_time:"8:55",bus_tick:"52元"},
{start:"定海",end:"余姚",end_station:"余姚",bus_time:"14:45",bus_tick:"52元"},
{start:"普陀",end:"启东",end_station:"启东",bus_time:"6:30",bus_tick:"215元"},
{start:"新城",end:"启东",end_station:"启东",bus_time:"6:50",bus_tick:"232元"},
{start:"定海",end:"启东",end_station:"启东",bus_time:"7:30",bus_tick:"227元"},
{start:"普陀",end:"东海",end_station:"东海",bus_time:"10:40",bus_tick:"294元"},
{start:"新城",end:"东海",end_station:"东海",bus_time:"11:05",bus_tick:"292元"},
{start:"定海",end:"东海",end_station:"东海",bus_time:"11:35",bus_tick:"288元"},
{start:"普陀",end:"衢州",end_station:"衢州",bus_time:"14:50",bus_tick:"150元"},
{start:"新城",end:"衢州",end_station:"衢州",bus_time:"15:10",bus_tick:"148元"},
{start:"定海",end:"衢州",end_station:"衢州",bus_time:"15:40",bus_tick:"144元"},
{start:"普陀",end:"汕头",end_station:"汕头",bus_time:"9:50",bus_tick:"425元"},
{start:"新城",end:"汕头",end_station:"汕头",bus_time:"10:08",bus_tick:"423元"},
{start:"定海",end:"汕头",end_station:"汕头",bus_time:"10:45",bus_tick:"420元"},
{start:"普陀",end:"石浦",end_station:"石浦",bus_time:"8:40",bus_tick:"100元"},
{start:"普陀",end:"石浦",end_station:"石浦",bus_time:"13:10",bus_tick:"100元"},
{start:"新城",end:"石浦",end_station:"石浦",bus_time:"9:00",bus_tick:"98元"},
{start:"新城",end:"石浦",end_station:"石浦",bus_time:"13:30",bus_tick:"98元"},
{start:"定海",end:"石浦",end_station:"石浦",bus_time:"9:35",bus_tick:"95元"},
{start:"定海",end:"石浦",end_station:"石浦",bus_time:"13:55",bus_tick:"95元"},
{start:"普陀",end:"天台",end_station:"天台",bus_time:"8:20",bus_tick:"95元"},
{start:"普陀",end:"天台",end_station:"天台",bus_time:"12:40",bus_tick:"95元"},
{start:"新城",end:"天台",end_station:"天台",bus_time:"8:40",bus_tick:"93元"},
{start:"新城",end:"天台",end_station:"天台",bus_time:"13:00",bus_tick:"93元"},
{start:"定海",end:"天台",end_station:"天台",bus_time:"9:10",bus_tick:"88元"},
{start:"定海",end:"天台",end_station:"天台",bus_time:"13:30",bus_tick:"88元"},
{start:"普陀",end:"许昌",end_station:"许昌",bus_time:"10:50",bus_tick:"440元"},
{start:"新城",end:"许昌",end_station:"许昌",bus_time:"11:15",bus_tick:"438元"},
{start:"定海",end:"许昌",end_station:"许昌",bus_time:"11:45",bus_tick:"435元"},
{start:"普陀",end:"镇海",end_station:"镇海",bus_time:"8:20",bus_tick:"45元"},
{start:"新城",end:"镇海",end_station:"镇海",bus_time:"8:40",bus_tick:"43元"},
{start:"定海",end:"镇海",end_station:"镇海",bus_time:"9:10",bus_tick:"40元"},
{start:"普陀",end:"玉环",end_station:"玉环",bus_time:"9:45",bus_tick:"123元"},
{start:"新城",end:"玉环",end_station:"玉环",bus_time:"10:05",bus_tick:"121元"},
{start:"定海",end:"玉环",end_station:"玉环",bus_time:"10:35",bus_tick:"116元"},
{start:"普陀",end:"苍南",end_station:"苍南",bus_time:"10:20",bus_tick:"147元"},
{start:"新城",end:"苍南",end_station:"苍南",bus_time:"10:40",bus_tick:"145元"},
{start:"定海",end:"苍南",end_station:"苍南",bus_time:"11:15",bus_tick:"140元"}
]